package com.familyfit.entity;

import jakarta.persistence.*;
import lombok.*;

import java.time.LocalDate;

/**
 * Computed health score for a family member on a given day.
 * Insight text is generated by {@link com.familyfit.service.HealthInsightGenerator}.
 */
@Entity
@Table(name = "health_scores")
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class HealthScore {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "member_id", nullable = false)
    private FamilyMember familyMember;

    @Column(nullable = false)
    private LocalDate date;

    /** 0–100 composite score */
    private int score;

    @Column(length = 500)
    private String insightText;
}
